/**
 * Image resolution — which slots have real photography (docs/07_IMAGES.md).
 *
 * The PHOTOS list between the markers is REGENERATED by `pnpm images`
 * (ingest-images.mjs); do not edit it by hand. Every slot resolves to its
 * optimized photograph when one exists, and to its placeholder art otherwise —
 * so photography arrives slot by slot with no code changes.
 */
const PHOTOS: ReadonlySet<string> = new Set<string>([
  // <photos>
  // </photos>
])

export function imageSrc(name: string): string {
  return PHOTOS.has(name) ? `/img/${name}.jpg` : `/img/${name}.svg`
}
